name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:  
  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.9.2'

      - run: meteor test-packages ./
